version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: telegram_messages
        description: Raw telegram messages data

models:
  - name: stg_telegram_messages
    description: Staging model for Telegram messages, cleaned and cast to correct types.
    columns:
      - name: message_id
        description: Primary key from source system.
        tests:
          - not_null
      - name: channel_name
        description: Name of the channel the message belongs to.
      - name: message_date
        description: Timestamp of when the message was sent (UTC).
        tests:
          - not_null
      - name: message_text
        description: Content of the message.
      - name: views
        description: Count of views.
      - name: forwards
        description: Count of forwards.
      - name: has_image
        description: Calculated boolean indicating if the message contains an image.
